### ISSUE TITLE
Docs and package are not in sync

### ISSUE THREAD

**Issue by Omicrxn** [Char2sGu/layout-projection#3]
The example on the docs and the API itself is not corresponding to the package API, like for example `const measurer = new ElementMeasurer(new CssBorderRadiusParser());` there is no ElementMeasurer. There are other examples but the docs don't correspond to the API

**Comment by Char2sGu** [comment]
Ah you caught me. This package is refactored to support more advanced animations, but the docs aren't yet updated. The API on the document corresponds to the v0.12 version.

**Comment by Omicrxn** [comment]
Hahaha you thought you would get away unnoticed 😜. No problem I'll be using version 0.12 until the docs are updated. Once they are I'll upgrade. Should work anyway right? Thanks!

**Comment by Char2sGu** [comment]
lol I never expected that someone would actually use this lib. I developed it primarily to do some layout animation in Angular. May I ask what is your use case?

**Comment by Omicrxn** [comment]
😢 hahaha if it works well I'll use it. I'm building an animation library for Svelte and I have FLIP animations which works quite well but I want to add layout projection instead, like framer.

**Comment by Char2sGu** [comment]
sounds neat. This library works. You could see https://reply.char2s.dev/ for a demo of https://github.com/Char2sGu/reply. However, now the view transition API has landed implementation, I thinnk Layout Projection would be deprecated in a few years.

**Comment by Omicrxn** [comment]
hmmm I'll take a look at View Transitions, but your project is really smooth ngl. Good work!

**Comment by Omicrxn** [comment]
Hey @Char2sGu in the end I think I'll go with layout projections, I'll migrateto view transitions when there is better support. However I can't get this to work in Svelte with the info from the docs, I get the overall idea but I have some questions, would it be possible to get into a call or something?

**Comment by Char2sGu** [comment]
In the meanwhile, this Stackblitz demo might help https://stackblitz.com/edit/layout-projection-example-list?file=index.ts&memory-freed=1
